filter:
    excluded_paths:
        - tests/*
        - vendor/*

build:
    environment:
        elasticsearch: true
        docker:
            cache:
                images:
                  - "*"
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
                coverage:
                    file: 'phpunit.report.coverage.xml'
                    format: 'clover'
