filter:
    excluded_paths:
        - tests/*
        - vendor/*
build:
    environment:
        elasticsearch: true

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
                coverage:
                    file: 'phpunit.report.coverage.xml'
                    format: 'clover'