language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
 - cd ..
 - git clone https://github.com/drupal/drupal
 - ln -s ~ drupal/modules/elasticentityquery
 - cd drupal
 - composer require elasticsearch/elasticsearch
 - composer install
 - cd core

script:
 - ../vendor/bin/phpunit --group=elasticentityquery --testsuite=unit
